# Generated by Django 5.2 on 2026-08-14 08:10

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('vehicle', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('manager_notes', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
