# Generated by Django 5.2 on 2026-08-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('E_RICKSHAW', 'E-Rickshaw'), ('CARGO', 'Cargo E-Rickshaw')], default='E_RICKSHAW', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('battery_capacity', models.CharField(blank=True, max_length=50)),
                ('range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('charging_time', models.CharField(blank=True, max_length=50)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_capacity', models.CharField(blank=True, max_length=50)),
                ('top_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('public_id', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
