# Generated by Django 5.2 on 2026-08-13 14:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDelivery',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_location', models.CharField(blank=True, max_length=150)),
                ('delivery_date', models.DateField()),
                ('image_url', models.URLField()),
                ('public_id', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
    ]
